[package]
name = "mini-sshd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
const_format = "0.2.32"
env_logger = "0.11.3"
log = "0.4.21"
num-derive = "0.4.2"
num-traits = "0.2.19"
ring = "0.17.8"
